### ISSUE TITLE
Update to RingCentral recipes

### ISSUE THREAD

**Issue by wegotoeleven** [autopkg/bradclare-recipes#24]
As per #23, updates to the RingCentral recipes to download the latest version of RingCentral.

**Comment by Balthamos** [comment]
Hello! I think this whole RingCentral issue is a bit more complex than it seemed at first glance.

This recipe, although titled RingCentral, was actually the recipe for the (still current) RingCentral product "[RC Phone](https://www.ringcentral.com/apps/rc-phone)" (also called RingCentral for Mac.app), which is not in fact at all related to the soon-to-be retired "[RingCentral Classic](https://support.ringcentral.com/article/Using-Latest-RingCentral-App.html)" app (originally called Glip.app) which is being replaced with a newer version simply called RingCentral.app.

The lightweight RC Phone app is a dedicated app to the calling, voicemail and texting features of RingCentral, and lacks all the extra (likely to many people unnecessary/unwanted) features present in the larger RingCentral Classic.app / RingCentral.app, which in addition to calling functionality, attempts to be a bit of a Slack alternative, with team IM, video conferencing, meetings, plugin-apps for third party connections, etc.

This recipe should probably have been renamed some time ago to RingCentral Phone, once the Glip app was renamed RingCentral.app (before being renamed again to RingCentral Classic). 

Now that the Classic app is fully going offline, the Classic recipe at [psaintmarie Repo](https://github.com/autopkg/psaintemarie-recipes) should likely be the one to be replaced with a recipe that downloads the primary RingCentral.app.

If RingCentral.app were in fact just an update to the RC Phone/RingCentral for Mac.app, or if the RC Phone app were being retired as the Classic Glip app is, then I would say this recipe change would be fine, however as it stands currently, with this change we'll now have a completely separate application being downloaded than the one people who use this recipe would be expecting.


For reference, here's a full list of the current RC-developed apps:
https://support.ringcentral.com/download.html

**Comment by wegotoeleven** [comment]
@Balthamos thanks for this review! I've consequently created a new PR (https://github.com/autopkg/bradclare-recipes/pull/25) that brings back the original recipes and changes a few details to better denote the app that they're for. This way, we don't need to make any additional changes to the RingCentral classic recipes at [psaintemarie-recipes]( https://github.com/autopkg/psaintemarie-recipes). How does this sound? Would be good to get your review before @bradclare approves this PR.

Thanks!

**Comment by wegotoeleven** [comment]
Also, I don't use Munki, so it would be great to test these Munki recipes and make any necessary changes.

**Comment by homebysix** [comment]
Just wanted to step in and give @Balthamos some extra kudos. That was a very thorough and helpful breakdown! ⭐

**Comment by Balthamos** [comment]
This looks good, thank you!
I tested the Munki Recipe's and they're both working properly. The only thing I might potentially change is the %NAME% key in the Munki recipe from "RingCentral Phone" to "RingCentralPhone". Don't think it makes any real difference but it seems like the norm is to have spaces in the display_name but not in the NAME/name variables?

Also, for both recipes, although this and the name thing above are easily fixable with the Recipe Override, it wouldn't hurt to have defaults set for
`<key>developer</key>
<string>RingCentral</string>
<key>category</key>
<string>Communication</string>`

Finally, I'm not entirely clear on why the following is now lacking but maybe one of you can enlighten me:
Previously, the override I was using to import the RingCentral.app into Munki would provide pkginfo keys for
`<key>blocking_applications</key>
<array>
<string>RingCentral.app</string>
</array>`
and an Installs array for the installed app, and now there's just a package receipt, but no Installs item.
From the looks of it, I wonder if it's because this Munki references as its parent the download.ringcentral recipe, whereas what I was using previously references the pkg.ringcentral recipe with the following Process arguments:
`<key>Process</key>
	<array>
		<dict>
			<key>Arguments</key>
			<dict>
				<key>faux_root</key>
				<string>%RECIPE_CACHE_DIR%/%NAME%</string>
				<key>installs_item_paths</key>
				<array>
					<string>/Applications/RingCentral.app</string>
				</array>
			</dict>
			<key>Processor</key>
			<string>MunkiInstallsItemsCreator</string>
		</dict>
		<dict>
			<key>Processor</key>
			<string>MunkiPkginfoMerger</string>
		</dict>
		<dict>
			<key>Arguments</key>
			<dict>
				<key>repo_subdirectory</key>
				<string>%MUNKI_REPO_SUBDIR%</string>
			</dict>
			<key>Processor</key>
			<string>MunkiImporter</string>
		</dict>
	</array>`


Anyway, thanks again for so quickly jumped on this!
